# Generated by Django 4.2.4 on 2023-09-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='logo',
        ),
    ]
