# Generated by Django 4.2.4 on 2023-09-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_myuser_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='active_session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
