# Generated by Django 4.2.4 on 2023-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_myuser_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
